FROM python:3.13.7-slim

WORKDIR /app

# Use buildx cache mounts for pip
RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade pip
RUN --mount=type=cache,target=/root/.cache/pip pip install paho-mqtt watchdog

# Copy code at build, but will be mounted in dev
COPY simulator/simulator.py ./

# Entrypoint for hot reload in development
CMD ["watchmedo", "auto-restart", "--directory=.", "--pattern=*.py", "--recursive", "--", "python", "simulator.py"]
